site_name: 浙江大学21年秋操作系统实验 
site_url: https://zjusec.gitee.io/os21fall/
theme:
  name: material
nav:
  - 实验指导零: lab0.md
  - 常见问题及解答: faq.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences